### ISSUE TITLE
Issue importing bh3 model 

### ISSUE THREAD

**Issue by CyberneticFox** [ptasev/Rise-of-Nations#2]
Hello I have been trying to import a model I created into Rise of nations with your plugin but I have been having some issues. When tried to export my model as a bh3 but when I try to import it back into Blender, Blender crashes to desktop. I tried to replace the mesh of the a10 with my model but I still have the issue. Then I tried to combine my model with a model from Rise of nations and then import it back into Blender. I get the following error Traceback (most recent call last):
  File "C:\Users\bmj40\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\riseofnations\__init__.py", line 52, in execute
    return file_importer.load(context, self.filepath)
  File "C:\Users\bmj40\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\riseofnations\blender\bh3fileimporter.py", line 54, in load
    uv_loops[loop.index].uv = self._file.uvs[loop.vertex_index]
IndexError: list index out of range Here are some screenshots of my model with its vertex groups as I think the issue is with bones and vertexes. 
![Screenshot 2024-04-03 210537](https://github.com/ptasev/Rise-of-Nations/assets/165971566/7dd1c816-de9f-4144-8af4-496ddba785cf)
![Screenshot 2024-04-03 210623](https://github.com/ptasev/Rise-of-Nations/assets/165971566/4344d3b8-a808-4013-a3dc-6b25db9e27c9)

**Comment by ptasev** [comment]
I can't tell what's going on from the info and screenshots. Can you send the original blend file that you are exporting?

**Comment by CyberneticFox** [comment]
Github said they don't support that file when I tried to move it here.

**Comment by yaofanggh** [comment]
> I can't tell what's going on from the info and screenshots. Can you send the blend file that you are exporting to BH3?

I think this is a great plugin, but there are almost no video tutorials on the web, so I suggest you take the time to make a very simple model and explain some of the key steps.

**Comment by HectorIII** [comment]
Hello, i was making a model for the rise of nation and i'm having the same problem, have any of you managed to solve this problem? And if so, how did you resolve it?

**Comment by yaofangwx123** [comment]
> Hello, i was making a model for the rise of nation and i'm having the same problem, have any of you managed to solve this problem? And if so, how did you resolve it?

 No.I give up.And now install window xp and 3ds max4,this add-on need to update for blender event I use blender2.8.1 and v2.0.0,,but it not work.

**Comment by ptasev** [comment]
The Blender Addon is no longer supported, but I just released the file converter app which will allow you to mod the models with Blender through glTF. Please give it a try and let me know if you have issue.

**Comment by HectorIII** [comment]
> The Blender Addon is no longer supported, but I just released the file converter app which will allow you to mod the models with Blender through glTF. Please give it a try and let me know if you have issue.

Hey, i return to try the mod i'm trying to make, about your file convertor, how's works this app? I try to downloas with all files but, after this, what's the process for converting BH3 files to BHA files?

Thanks for your work anf you asking BTW.

**Comment by ptasev** [comment]
I put some steps together recently for issue #5. You have to use the command prompt, powershell, or [terminal](https://aka.ms/terminal).
